workspace:
  base: /test
  path: oe_corporate_site_info

services:
  web:
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    environment:
      - DOCUMENT_ROOT=/test/oe_corporate_site_info
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  sparql:
    image: openeuropa/triple-store-dev:1.4.0
    pull: true
    environment:
      - SPARQL_UPDATE=true
      - DBA_PASSWORD=dba
  selenium:
    image: selenium/standalone-chrome:3.141.59-oxygen
    pull: true
    shm_size: 2g
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=800

pipeline:
  composer-install:
    group: prepare
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    volumes:
      - /cache:/cache
    commands:
      - composer install --ansi --no-suggest --no-progress

  composer-update-lowest:
    group: post-prepare
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    volumes:
      - /cache:/cache
    commands:
      # @todo remove "composer install" step once the following issue is fixed.
      # @link https://webgate.ec.europa.eu/CITnet/jira/browse/OPENEUROPA-1234
      - composer update --prefer-lowest --prefer-stable --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  site-install:
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    commands:
      - ./vendor/bin/run drupal:site-install

  grumphp:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    commands:
      - ./vendor/bin/phpunit

  behat:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    commands:
      - ./vendor/bin/behat --strict

  debug:
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    commands:
      - ./vendor/bin/drush ws --count 500
    when:
      status: failure

matrix:
  COMPOSER_BOUNDARY:
    - lowest
    - highest
  PHP_VERSION:
    - 7.2
    - 7.3
