# Expose our configuration to the translation system
oe_corporate_site_info.settings:
  title: 'OE Corporate site info settings'
  base_route_name: system.site_information_settings
  names:
    - oe_corporate_site_info.settings
