<?php

/**
 * @file
 * OpenEuropa Corporate Site Information module.
 */

declare(strict_types = 1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\multivalue_form_element\Element\MultiValue;
use Drupal\rdf_skos\Entity\ConceptInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function oe_corporate_site_info_form_system_site_information_settings_alter(&$form, FormStateInterface $form_state, $form_id): void {
  $corporate_site_info = \Drupal::config('oe_corporate_site_info.settings');
  $skos_concept_storage = \Drupal::entityTypeManager()->getStorage('skos_concept');

  $form['oe_site_information'] = [
    '#type' => 'details',
    '#title' => t('Corporate site information'),
    '#open' => TRUE,
  ];

  $site_owner = $corporate_site_info->get('site_owner') ?? NULL;
  $site_owner_entity = NULL;
  if ($site_owner) {
    $site_owner_entity = $skos_concept_storage->load($site_owner);
  }

  $form['oe_site_information']['site_owner'] = [
    '#title' => t('Site owner'),
    '#type' => 'entity_autocomplete',
    '#target_type' => 'skos_concept',
    '#selection_handler' => 'default:skos_concept',
    '#selection_settings' => [
      'concept_schemes' => [
        'http://publications.europa.eu/resource/authority/corporate-body',
      ],
      'concept_subset' => 'oe_corporate_site_info_corporate_bodies_department_executive_agencies',
      'match_operator' => 'CONTAINS',
      'match_limit' => 10,
    ],
    '#maxlength' => 1024,
    '#default_value' => $site_owner_entity,
    '#required' => TRUE,
    '#size' => 60,
    '#placeholder' => '',
  ];

  $content_owner_ids = $corporate_site_info->get('content_owners') ?? [];
  $content_owners_entities = [];
  foreach ($content_owner_ids as $key => $content_owner_id) {
    $skos_entity = $skos_concept_storage->load($content_owner_id);
    if ($skos_entity instanceof ConceptInterface) {
      $content_owners_entities[] = $skos_entity;
    }
  }

  $form['oe_site_information']['content_owners'] = [
    '#type' => 'multivalue',
    '#cardinality' => MultiValue::CARDINALITY_UNLIMITED,
    '#title' => t('Default content owner(s)'),
    '#required' => TRUE,
    'target' => [
      '#type' => 'entity_autocomplete',
      '#title' => t('Content owner'),
      '#title_display' => 'invisible',
      '#target_type' => 'skos_concept',
      '#selection_handler' => 'default:skos_concept',
      '#selection_settings' => [
        'concept_schemes' => [
          'http://publications.europa.eu/resource/authority/corporate-body',
        ],
        'concept_subset' => 'oe_corporate_site_info_corporate_bodies_department_executive_agencies',
        'match_operator' => 'CONTAINS',
        'match_limit' => 10,
      ],
      '#maxlength' => 1024,
      '#size' => 60,
      '#placeholder' => '',
    ],
    '#default_value' => $content_owners_entities,
    '#description' => t('This is not the writer of the content, but the subject matter expert responsible for keeping this content up to date. <br>When this field is populated, it will provide the default Content owner for all new content on this website. It can be overwritten for every new item.'),
  ];

  // SiteInformationForm::submitForm calls the parent ::submitForm,
  // so we need to add our submit function to the beginning of the list
  // to give it a chance to execute.
  array_unshift($form['#submit'], '_oe_corporate_site_info_settings_form_submit');
}

/**
 * Submit handler for site information settings form.
 *
 * @param $form
 *   The form elements array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state array.
 */
function _oe_corporate_site_info_settings_form_submit(&$form, FormStateInterface $form_state): void {
  $corporate_site_info = \Drupal::configFactory()->getEditable('oe_corporate_site_info.settings');
  $corporate_site_info->set('site_owner', $form_state->getValue('site_owner'));
  $content_owner_ids = array_column($form_state->getValue('content_owners', []), 'target');
  $corporate_site_info->set('content_owners', $content_owner_ids);
  $corporate_site_info->save();
}
