oe_corporate_site_info.settings:
  type: config_object
  label: 'OpenEuropa Corporate site information'
  mapping:
    site_owner:
      type: string
      label: 'Site owner SKOS entity ID'
    content_owners:
      label: 'Content owners SKOS entities'
      type: sequence
      sequence:
        label: 'SKOS entity id with weight'
        type: mapping
        mapping:
          target:
            type: string
            label: 'SKOS entity ID'
          weight:
            type: integer
            label: 'Weight'
